### ISSUE TITLE
[Fix - Session 8] Link zum Ggplot CheatSheet funktioniert nicht

### ISSUE THREAD

**Issue by cosimameyer** [CorrelAid/lernplattform#11]
- Link einbauen

**Comment by cosimameyer** [comment]
@friep @ZoeWolter das ist mir gestern eingefallen als ich Fries Ticketflut gesehen habe 😄 Der Link *müsste* funktionieren und sieht richtig aus (die Datei ist auch da) - könntet ihr das, wenn die Zeit da ist, nochmal vor dem Release überprüfen? Danke!

**Comment by ZoeWolter** [comment]
@cosimameyer Hab den "Schummelzettel"-Link und auch den zu "Session 5" nochmal angepasst - danke, dass dir das aufgefallen ist! - und auch schon deployed, magst du vielleicht nochmal überprüfen, ob alles passt? https://correlaid.shinyapps.io/lernplattform/#section-datenvisualisierung-1

**Comment by cosimameyer** [comment]
Perfekt, danke! Es passt bei allen, nur hier nicht: 
![9C54DE20-A8A8-4370-845E-B054298E59BE](https://user-images.githubusercontent.com/7782895/224284070-c58f8e47-884e-40f3-9e92-5f108b1408a3.jpeg)

**Comment by ZoeWolter** [comment]
Oh wow, danke für die super schnelle Rückmeldung! Ist angepasst :)
