### ISSUE TITLE
Reproduzierbarkeit / Package Versionen 

### ISSUE THREAD

**Issue by friep** [CorrelAid/lernplattform#14]
Es ist schwierig, das Projekt lokal zum Laufen zu bringen. 

beispielhaft: 

Zeile 151 in `lernplattform.Rmd` 

`dplyr::na_if` als Problem. 

z.B. renv

**Comment by tbaldenius** [comment]
Mir ist gerade aufgefallen, dass dplyr::na_if in Zeile 471 von 07_ als Teil einer Aufgabenstellung auftaucht. na_if kann seit dplyr 1.1 nich mehr auf tibbles/data.frames angewendet werden, nur noch auf Vektoren. Möglich ist `mutate(across(where(is.numeric), ~ dplyr::na_if(.x, -99)))`, aber ist das vielleicht etwas kompliziert für den Kurs?

**Comment by friep** [comment]
Super mitgedacht :) 
das würde ich an das inhaltliche Team geben, da das eine didaktische Entscheidung ist. @tbaldenius magst du das (mit Link hierhin) in den Slack channel `rlernen-planning` posten?

**Comment by friep** [comment]
habe das nun implementiert (siehe 94c9aba6303988cf460f1031a8fa963864bff8bf ) und auf main gepusht, da ich sonst die aktuelle Lektion nicht hätte deployen können.  danke @tbaldenius . 

ich mache einen neuen issue auf für `renv`.
