### ISSUE TITLE
Fehler bei 07_datentransformation.Rmd

### ISSUE THREAD

**Issue by zeidli** [CorrelAid/lernplattform#28]
Bei der Datei 07_datentransformation steckt ein kleiner Fehler.
Es fehlt bei Zeile 281 bei der Zuweisung 
community <- plastics_processed %>%
das plastics_processed in der Datei.
Ich vermute es steckt data_raw dahinter.

**Comment by ZoeWolter** [comment]
@zeidli Ich glaube hier verstehe ich nicht ganz was du meinst? Vielleicht kannst du das einfach nochmal erläutern :) 
`plastics_processed` laden wir ja schon in `lernplattform.Rmd` oder verstehe ich dich hier falsch?
