### ISSUE TITLE
kleiner Error beim Filtern 07_datentransformation.Rmd 

### ISSUE THREAD

**Issue by zeidli** [CorrelAid/lernplattform#30]
Bei der Zeile 180 gibt es einen kleinen Fehler, statt dem Jahr 2020 wird das Jahr 2019 gefiltert

#### Ihr nehmt Euren Datensatz...
data_raw %>%
  #### ..filtert "EMPTY", "Grand Total" und Jahr 2020 heraus
  dplyr::filter(country != "EMPTY",
                parent_company != "Grand Total", 
                year == 2019 
                )
`
Sauberer wäre als Lösung: year!=2020, wird auch unten angeführt

**Comment by ZoeWolter** [comment]
Danke für die Anmerkung! Im Datensatz soll ja nur noch das Jahr 2019 übrig bleiben, d.h. wir können bei dem Datensatz hier tatsächlich entweder über year == 2019 oder year != 2020 filtern, falls aber noch andere Werte als 2019 und 2020 in der Variablen vorkommen, ist year == 2019 die sicherere Variante, um wirklich nur dieses Jahr noch zu behalten. 
Habe den Kommentar im Code aber geändert, glaube der war etwas missverständlich!
