### ISSUE TITLE
[12_rshiny/Shiny] Einheitliche Bezeichnung

### ISSUE THREAD

**Issue by cosimameyer** [CorrelAid/lernplattform#36]
In der Session selbst verwenden wir einheitlich "Shiny-App", in der verlinkten [App](https://correlaid.shinyapps.io/breakfreefromplastic/) steht aber "Shiny Web Apps":

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/7782895/232183028-1d433236-d69f-4d43-bec6-b2560f4ef863.png">

-> hier auch "Shiny-Apps" anstatt "Shiny Web Apps" verwenden

**Comment by ZoeWolter** [comment]
@cosimameyer @ninahauserberlin Wo finde ich denn den Code / das Repo zur App?

**Comment by cosimameyer** [comment]
Ich denke die wird separat gehostet. @ninahauserberlin oder @friep müssten das wissen.

**Comment by ninahauserberlin** [comment]
Hosting auf unserer shinyapps.io-Instanz

**Comment by ZoeWolter** [comment]
Merci!
