### ISSUE TITLE
karte.R / karte.Rmd

### ISSUE THREAD

**Issue by ZoeWolter** [CorrelAid/lernplattform#42]
@cosimameyer Sind die Dateien `tbd/karte.R` und `tbd/karte.Rmd` noch relevant oder werden die ohnehin nicht mehr gebraucht?

**Comment by cosimameyer** [comment]
Ich bin nicht sicher woher der kommt. In der ersten Iteration hatte ich echarts4r als minimalistisch Lösung implementiert, dann kam leaflet (das scheint der Code zu sein - @ninahauserberlin weißt du mehr?) was auch nicht ideal war. Daraufhin habe ich [dieses Issue](https://github.com/CorrelAid/lernplattform/issues/8) aufgemacht - ich glaube wir müssen uns entscheiden, wie wir es aufziehen wollen.

**Comment by ninahauserberlin** [comment]
Legacy code - liegt daran, dass wir uns nicht final zwischen den beiden Packages entschieden haben

**Comment by ZoeWolter** [comment]
Alles klar, danke!
